### ISSUE TITLE
EditWithIdleX.py keeps failing due to 3 errors

### ISSUE THREAD

**Issue by TheBurntLight** [serwy/idlex#11]
Here are the errors:

Traceback (most recent call last):
  File "C:\Python37\Scripts\EditWithIdleX.py", line 194, in <module>
    build_gui()
  File "C:\Python37\Scripts\EditWithIdleX.py", line 162, in build_gui
    "Python found at: %r" % get_python_executable(),
  File "C:\Python37\Scripts\EditWithIdleX.py", line 65, in get_python_executable
    p = W.OpenKey(reg, r'Python.File\shell\Edit with IDLE\command')
FileNotFoundError: [WinError 2] The system cannot find the file specified

Currently Using Python 3.7.2

**Comment by DefinitelyNotAnAlien** [comment]
Maybe it would be better to use sys.executable [(Python 2 docs)](https://docs.python.org/2/library/sys.html#sys.executable) [(Python 3 docs)](https://docs.python.org/3/library/sys.html#sys.executable) to find the path to the Python executable?
Looks like there can be several editwithidle commands in the registry depending on which Python versions have been installed.

**Comment by TheBurntLight** [comment]
Only one version has been installed

**Comment by nkoeppel** [comment]
What the previous comment was suggesting something like simply replace the get_python_executable() function with sys.executable and it should work.

**Comment by Coincoin35** [comment]
> 
> What the previous comment was suggesting something like simply replace the get_python_executable() function with sys.executable and it should work.

This works: I replaced get_python_executable() by the standrd string to get this path i.e., _**sys.executable**_
https://docs.python.org/3/library/sys.html

> line 95: path_to_python = sys.executable #get_python_executable()
> line 162: "Python found at: %r" % sys.executable, #get_python_executable()

then launch again the script. --> feb 2021, windows 10 up-to-date, python3.9.2 amd64 (evenif no python2.7 installed in parallel which may cause some mess).

**Comment by Gobline225** [comment]
in the EditWIthIdleX.py remplace the `p = W.OpenKey(reg, r'Python.File\shell\Edit with IDLE\command')` by 
`p = W.OpenKey(reg, r'Python.File\shell\editwithidle\shell\edit310\command')` that will solve your problem.

**Comment by Gobline225** [comment]
> Here are the errors:
> 
> Traceback (most recent call last): File "C:\Python37\Scripts\EditWithIdleX.py", line 194, in build_gui() File "C:\Python37\Scripts\EditWithIdleX.py", line 162, in build_gui "Python found at: %r" % get_python_executable(), File "C:\Python37\Scripts\EditWithIdleX.py", line 65, in get_python_executable p = W.OpenKey(reg, r'Python.File\shell\Edit with IDLE\command') FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
> Currently Using Python 3.7.2

in the EditWIthIdleX.py remplace the `p = W.OpenKey(reg, r'Python.File\shell\Edit with IDLE\command')` by 
`p = W.OpenKey(reg, r'Python.File\shell\editwithidle\shell\edit310\command')` that will solve your problem
<img width="782" alt="Capture d’écran 2022-08-07 160657" src="https://user-images.githubusercontent.com/65910991/183300150-5e563edc-1ee6-46a3-8d43-a9b7679f932c.png">
.

**Comment by ahmadmysra** [comment]
>
> > in the EditWIthIdleX.py remplace the `p = W.OpenKey(reg, r'Python.File\shell\Edit with IDLE\command')` by `p = W.OpenKey(reg, r'Python.File\shell\editwithidle\shell\edit310\command')` that will solve your problem .
> >
>
> >
>  This worked for me after changing `edit310` to `edit311`
>  Currently using Python 3.11.2
